# Generated by Django 5.1.6 on 2025-02-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_company_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
    ]
