# Generated by Django 5.1.6 on 2025-02-25 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0010_alter_user_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="rolemenupermissions",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="rolemenupermissions",
            constraint=models.UniqueConstraint(
                fields=("role", "menu"), name="unique_role_menu_permission"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="login.role",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
