# Generated by Django 5.1.6 on 2025-02-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0011_profile_alter_rolemenupermissions_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="domain",
        ),
    ]
