# Generated by Django 5.1.6 on 2025-02-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0012_remove_company_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AlterField(
            model_name="company",
            name="schema_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
